### ISSUE TITLE
[FF Extension] Any action invokes the wrath of the pop-up blocker

### ISSUE THREAD

**Issue by dxprog** [dxprog/reddit-booru#5]

**Comment by AlexKolpa** [comment]
using `window.open` from JS directly does indeed trigger the wrath of Firefox's pop-up blocker. Instead, you could use `sdk/window/utils`'s `open` function instead: https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/window_utils#open(uri.2C_options). I did a quick local test and it seemed to work (though I had to do it in a new environment since the Firefox extension's setup seems to be deprecated).

**Comment by HigherFive** [comment]
Nice.

**Comment by dxprog** [comment]
This has been resolved in the soon-to-be-published new browser extension: https://github.com/dxprog/rb-browser-ext
